### ISSUE TITLE
No responses on the popup window

### ISSUE THREAD

**Issue by TheAvocadoProtocol** [kawamataryo/chikamichi#15] opened 2022-01-31 15:35 UTC
Hi!

I have this problem with the extension on chrome 

Currently, I'm using: 
- Chrome v 97.0.4692.99
- macOS BigSur v11.6.2

When I press `opt + k` the popup window opens, but it doesn't respond to any events, no click or keyboard search.

https://user-images.githubusercontent.com/96927020/151822960-7252c305-4b0c-4a0d-8242-4c1f6dbaf396.mov

**Comment by kawamataryo** [comment] 2022-01-31 21:48
Hi. thanks for issue.

I can't reproduce it here, so I'd like to know more about it.
Can you please try the following.

1. Are you seeing any errors in the popup window devtools? If so, please tell us what it is.
2. Can you please check if any other Chrome extensions are affecting it

https://user-images.githubusercontent.com/11070996/151878503-37846ed3-c0f5-4d88-b111-faab12e96030.mp4

**Comment by kawamataryo** [comment] 2022-02-12 00:35
Since there is no reply, I will close it once.
Please open it again if you need anything else.

**Closed by kawamataryo** 2022-02-12 00:35 UTC
